# Generated by Django 6.0.3 on 2026-03-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_secciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='plazo',
        ),
        migrations.AddField(
            model_name='seccion',
            name='plazo_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seccion',
            name='porcentaje_cumplimiento',
            field=models.IntegerField(default=0),
        ),
    ]
