# Generated by Django 6.0.3 on 2026-03-07 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_secciones', '0002_remove_seccion_plazo_seccion_plazo_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plazo', models.CharField(max_length=200)),
                ('fecha_limite', models.DateField()),
                ('fecha_cumplimiento', models.DateField(blank=True, null=True)),
                ('radicado', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_secciones.seccion')),
            ],
        ),
    ]
