# Generated by Django 6.0.3 on 2026-03-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_secciones', '0003_plazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plazo',
            name='tipo_plazo',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral')], default='Mensual', max_length=20),
        ),
    ]
