# Generated by Django 6.0.3 on 2026-03-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_secciones', '0004_plazo_tipo_plazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plazo',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Cumplido', 'Cumplido')], default='Pendiente', max_length=20),
        ),
    ]
