# Generated by Django 6.0.3 on 2026-03-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_secciones', '0005_alter_plazo_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='plazo_total',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='porcentaje_cumplimiento',
        ),
        migrations.AlterField(
            model_name='seccion',
            name='nombre_seccion',
            field=models.CharField(max_length=50),
        ),
    ]
