# Generated by Django 6.0.3 on 2026-03-15 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_secciones', '0007_seccion_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plazo',
            name='radicado',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
    ]
