# Generated by Django 6.0.3 on 2026-03-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_secciones', '0008_alter_plazo_radicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='plazo',
            name='periodo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
